---
- name: Creating Windows Pwn directory in "{{ pwn_win_dir }}"
  file:
    path: "{{ pwn_win_dir }}"
    state: directory
    owner: "{{ user_dir }}"
    mode: '0755'
  become: yes

- name: Cloning Windows Focused tools 
  git:
    repo: "{{ item }}"
    dest: "{{ pwn_win_dir }}{{ item.split('/')[-1].replace('.git','')}}"
    version: master
  loop:
    - https://github.com/BloodHoundAD/BloodHound
    - https://github.com/byt3bl33d3r/CrackMapExec
    - https://github.com/trustedsec/unicorn
    - https://github.com/Hackplayers/evil-winrm
    - https://github.com/PowerShellMafia/PowerSploit.git  
    - https://github.com/GhostPack/KeeThief
    - https://github.com/GhostPack/Seatbelt
    - https://github.com/GhostPack/SharpUp
    - https://github.com/GhostPack/SafetyKatz
    - https://github.com/GhostPack/SharpDump
    - https://github.com/GhostPack/SharpWMI  
    - https://github.com/GhostPack/Rubeus
    - https://github.com/GhostPack/SharpDPAPI
    - https://github.com/GhostPack/Lockless
    - https://github.com/GhostPack/SharpRoast
    - https://github.com/cobbr/PSAmsi.git
    - https://github.com/Tylous/Limelighter
  become: yes

- name: Downloading precompiled Packages
  get_url:
    url: "{{ item }}"
    dest: "{{ pwn_win_dir }}"
    mode: 644
    owner: "{{ user_dir }}"
  loop:
    - https://download.sysinternals.com/files/SysinternalsSuite.zip
    - https://github.com/gentilkiwi/mimikatz/releases/download/2.2.0-20200918-fix/mimikatz_trunk.zip
  become: yes
